version: '3.8'

services:
  mysqldb:
    image: mysql:8.0
    container_name: mysqldb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: Password1
      MYSQL_DATABASE: LMS
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  backend:
    image: lms-backend
    container_name: springboot-backend
    restart: unless-stopped
    depends_on:
      - mysqldb
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/LMS
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Password1
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect
      SERVER_ADDRESS: 0.0.0.0
      SPRING_CORS_ALLOWED_ORIGINS: "*"
    ports:
      - "8080:8080"
    networks:
      - app-network

  frontend:
    image: library-frontend
    container_name: angular-frontend
    depends_on:
      - backend
    ports:
      - "80:80"
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge
